---
title: Future Applications of MicroPs
description: "Inspired by some cool Youtube videos"
author: "Ellie Sundheim"
date: "10/31/24"
categories:
  - reflection
draft: false
---
I've been thinking about how I'll use my very expensive education after college. For HSA classes, I never expected them to be useful, so that's not a problem. Most of them I enjoyed in the moment. I still pull out fun facts and make random connections to other topics and sound well-rounded when I talk to other people, and that's all I wanted out of my humanities anyway. For some of my classes, like E72 or E&M, I'll continue to use tools built on the fundamental concepts they teach, like Fourier series and magnetic fields, even if I don't necessarily develop them from first principles again. Some of my classes, like E83, I will just appreciate what my mech E colleagues think about (from a safe distance). But MicoPs (and perahps a select few others), I hope and expect to use for both work and personal projects. Work, I already know, will involve microcontrollers to some extent. I hope I can use more interesting ones than Arduinos - my background in E155 should be enough for me to make educated guesses about what an Arduino is and is not capable of, and why I might want a different microcontroller with other peripherals. Personal projects are where it gets fun. I rejected a suggestion of my dad's for the final project for being "too simple," but it is something I can see myself making for him as a gift - a sensor to see if the garage door is open, since my mom and siblings have a tendency to forget about it. Maybe I'll make it like the temperature sensor in lab 6 so he can check it from anywhere, and even close it. My dad has also wanted to make some sort of candy delivery system for Halloween for a while, and I finally think I have the skills to make it cool and not lame. I think he wanted the screaming monkeys from the Wizard of Oz crossed with a Rube Goldberg machine, and with my new knowledge of speakers and motors, I think I can inflict some serious pyschic damage on unsuspecting trick-or-treaters. Hopefully, my $80,000/18 credits * 4 credits = 17,000 dollars of microPs tuition is worth it.
