---
title: ChatGPT, the musician
description: "Merrily, merrily, merrily, merrily, life is but a dream"
author: "Ellie Sundheim"
date: "10/4/24"
categories:
  - reflection
draft: false
---
For this week's lab, I built a system that can play music, provided that it is rendered as an array of pitches and durations. Sheet music already encodes this information in a way that is great for human musicians, but less so for microcontrollers. To bridge the gap, I translated a page of sheet music into two Excel columns of notes (e.g. C4, A4, Bb4) and durations (e.g. whole note = 1, quarter note = 0.25, tied half-quarter notes = 0.75). I then manually changed notes to frequencies and played around with a scaling factor to get durations in milliseconds. To be honest, this part was slightly tedious and I was complaining to my labmate Marina, who suggested that I use ChatGPT instead. Credit where credit is due, this was a great idea. \

ChatGPT was willing to humor my request to "write a song in the format (pitch, duration) where pitch is in Hz and duration is in milliseconds." I decided to ask for a recognizable tune of "Row, Row, Row Your Boat," figuing that the internet probably has plenty of examples of this for fourth-graders with recorders. With some guidance, it spat out a nicely formatted C array, including comments, of each note and the lyrics it corresponded to. On first glance, it looked pretty decent! However, on further inspection it was missing word and missing obvious patterns (decending in pitch on the merrily's). When played, it didn't sound remotely close:\
{{< video https://youtube.com/shorts/1s1L2aoM1w4 >}}

I tried getting it to give me the notes separately, because it did fine converting notes to pitches, but it didn't do any better. In conclusion, I think I could have used it to save me some time turning notes into frequencies and fomatting it into a C array, but I would need to get the melody into notes first. Too bad ChatGPT's parents didn't make it take piano lessons for all of elementary school!


